import type { Country } from '@models/data/country';

export const africaData: Country[] = [
  { id: 'AO', country: 'Angola', capital: 'Luanda' },
  { id: 'BI', country: 'Burundi', capital: 'Gitega' },
  { id: 'BJ', country: 'Bénin', capital: 'Porto-Novo' },
  { id: 'BF', country: 'Burkina Faso', capital: 'Ouagadougou' },
  { id: 'BW', country: 'Botswana', capital: 'Gaborone' },
  { id: 'CF', country: 'République centrafricaine', capital: 'Bangui' },
  { id: 'CI', country: "Côte d'Ivoire", capital: 'Yamoussoukro' },
  { id: 'CM', country: 'Cameroun', capital: 'Yaoundé' },
  {
    id: 'CD',
    country: 'République démocratique du Congo',
    capital: 'Kinshasa',
  },
  { id: 'CG', country: 'République du Congo', capital: 'Brazzaville' },
  { id: 'DJ', country: 'Djibouti', capital: 'Djibouti' },
  { id: 'DZ', country: 'Algérie', capital: 'Alger' },
  { id: 'EG', country: 'Égypte', capital: 'Le Caire' },
  { id: 'ER', country: 'Érythrée', capital: 'Asmara' },
  { id: 'ET', country: 'Éthiopie', capital: 'Addis-Abeba' },
  { id: 'GA', country: 'Gabon', capital: 'Libreville' },
  { id: 'GH', country: 'Ghana', capital: 'Accra' },
  { id: 'GN', country: 'Guinée', capital: 'Conakry' },
  { id: 'GM', country: 'Gambie', capital: 'Banjul' },
  { id: 'GW', country: 'Guinée-Bissau', capital: 'Bissau' },
  { id: 'GQ', country: 'Guinée équatoriale', capital: 'Malabo' },
  { id: 'KE', country: 'Kenya', capital: 'Nairobi' },
  { id: 'LR', country: 'Liberia', capital: 'Monrovia' },
  { id: 'LY', country: 'Libye', capital: 'Tripoli' },
  { id: 'LS', country: 'Lesotho', capital: 'Maseru' },
  { id: 'MA', country: 'Maroc', capital: 'Rabat' },
  { id: 'MG', country: 'Madagascar', capital: 'Antananarivo' },
  { id: 'ML', country: 'Mali', capital: 'Bamako' },
  { id: 'MZ', country: 'Mozambique', capital: 'Maputo' },
  { id: 'MR', country: 'Mauritanie', capital: 'Nouakchott' },
  { id: 'MW', country: 'Malawi', capital: 'Lilongwe' },
  { id: 'NA', country: 'Namibie', capital: 'Windhoek' },
  { id: 'NE', country: 'Niger', capital: 'Niamey' },
  { id: 'NG', country: 'Nigeria', capital: 'Abuja' },
  { id: 'RW', country: 'Rwanda', capital: 'Kigali' },
  { id: 'EH', country: 'Sahara occidental', capital: 'Laâyoune' },
  { id: 'SD', country: 'Soudan', capital: 'Khartoum' },
  { id: 'SS', country: 'Soudan du Sud', capital: 'Djouba' },
  { id: 'SN', country: 'Sénégal', capital: 'Dakar' },
  { id: 'SL', country: 'Sierra Leone', capital: 'Freetown' },
  { id: 'SZ', country: 'Eswatini', capital: 'Mbabane' },
  { id: 'TD', country: 'Tchad', capital: 'Ndjamena' },
  { id: 'TG', country: 'Togo', capital: 'Lomé' },
  { id: 'TN', country: 'Tunisie', capital: 'Tunis' },
  { id: 'TZ', country: 'Tanzanie', capital: 'Dodoma' },
  { id: 'UG', country: 'Ouganda', capital: 'Kampala' },
  { id: 'ZA', country: 'Afrique du Sud', capital: 'Pretoria' },
  { id: 'ZM', country: 'Zambie', capital: 'Lusaka' },
  { id: 'ZW', country: 'Zimbabwe', capital: 'Harare' },
  { id: 'SO', country: 'Somalie', capital: 'Mogadiscio' },
];
