import type { Country } from '@models/data/country';

export const africaData: Country[] = [
  { id: 'AO', country: 'Angola', city: 'Luanda' },
  { id: 'BI', country: 'Burundi', city: 'Gitega' },
  { id: 'BJ', country: 'Bénin', city: 'Porto-Novo' },
  { id: 'BF', country: 'Burkina Faso', city: 'Ouagadougou' },
  { id: 'BW', country: 'Botswana', city: 'Gaborone' },
  { id: 'CF', country: 'République centrafricaine', city: 'Bangui' },
  { id: 'CI', country: "Côte d'Ivoire", city: 'Yamoussoukro' },
  { id: 'CM', country: 'Cameroun', city: 'Yaoundé' },
  {
    id: 'CD',
    country: 'République démocratique du Congo',
    city: 'Kinshasa',
  },
  { id: 'CG', country: 'République du Congo', city: 'Brazzaville' },
  { id: 'DJ', country: 'Djibouti', city: 'Djibouti' },
  { id: 'DZ', country: 'Algérie', city: 'Alger' },
  { id: 'EG', country: 'Égypte', city: 'Le Caire' },
  { id: 'ER', country: 'Érythrée', city: 'Asmara' },
  { id: 'ET', country: 'Éthiopie', city: 'Addis-Abeba' },
  { id: 'GA', country: 'Gabon', city: 'Libreville' },
  { id: 'GH', country: 'Ghana', city: 'Accra' },
  { id: 'GN', country: 'Guinée', city: 'Conakry' },
  { id: 'GM', country: 'Gambie', city: 'Banjul' },
  { id: 'GW', country: 'Guinée-Bissau', city: 'Bissau' },
  { id: 'GQ', country: 'Guinée équatoriale', city: 'Malabo' },
  { id: 'KE', country: 'Kenya', city: 'Nairobi' },
  { id: 'LR', country: 'Liberia', city: 'Monrovia' },
  { id: 'LY', country: 'Libye', city: 'Tripoli' },
  { id: 'LS', country: 'Lesotho', city: 'Maseru' },
  { id: 'MA', country: 'Maroc', city: 'Rabat' },
  { id: 'MG', country: 'Madagascar', city: 'Tananarive' },
  { id: 'ML', country: 'Mali', city: 'Bamako' },
  { id: 'MZ', country: 'Mozambique', city: 'Maputo' },
  { id: 'MR', country: 'Mauritanie', city: 'Nouakchott' },
  { id: 'MW', country: 'Malawi', city: 'Lilongwe' },
  { id: 'NA', country: 'Namibie', city: 'Windhoek' },
  { id: 'NE', country: 'Niger', city: 'Niamey' },
  { id: 'NG', country: 'Nigeria', city: 'Abuja' },
  { id: 'RW', country: 'Rwanda', city: 'Kigali' },
  { id: 'EH', country: 'Sahara occidental', city: 'Laâyoune' },
  { id: 'SD', country: 'Soudan', city: 'Khartoum' },
  { id: 'SS', country: 'Soudan du Sud', city: 'Djouba' },
  { id: 'SN', country: 'Sénégal', city: 'Dakar' },
  { id: 'SL', country: 'Sierra Leone', city: 'Freetown' },
  { id: 'SZ', country: 'Eswatini', city: 'Mbabane' },
  { id: 'TD', country: 'Tchad', city: "N'Djamena" },
  { id: 'TG', country: 'Togo', city: 'Lomé' },
  { id: 'TN', country: 'Tunisie', city: 'Tunis' },
  { id: 'TZ', country: 'Tanzanie', city: 'Dodoma' },
  { id: 'UG', country: 'Ouganda', city: 'Kampala' },
  { id: 'ZA', country: 'Afrique du Sud', city: 'Pretoria' },
  { id: 'ZM', country: 'Zambie', city: 'Lusaka' },
  { id: 'ZW', country: 'Zimbabwe', city: 'Harare' },
  { id: 'SO', country: 'Somalie', city: 'Mogadiscio' },
];
