import type { Department } from '@models/data/department';

export const fraDptData: Department[] = [
  { id: '01', department: 'Ain', city: 'Bourg-en-Bresse' },
  { id: '02', department: 'Aisne', city: 'Laon' },
  { id: '03', department: 'Allier', city: 'Moulins' },
  { id: '04', department: 'Alpes de Haute-Provence', city: 'Digne-les-Bains' },
  { id: '05', department: 'Hautes-Alpes', city: 'Gap' },
  { id: '06', department: 'Alpes-Maritimes', city: 'Nice' },
  { id: '07', department: 'Ardêche', city: 'Privas' },
  { id: '08', department: 'Ardennes', city: 'Charleville-Mézières' },
  { id: '09', department: 'Ariège', city: 'Foix' },
  { id: '10', department: 'Aube', city: 'Troyes' },
  { id: '11', department: 'Aude', city: 'Carcassonne' },
  { id: '12', department: 'Aveyron', city: 'Rodez' },
  { id: '13', department: 'Bouches-du-Rhône', city: 'Marseille' },
  { id: '14', department: 'Calvados', city: 'Caen' },
  { id: '15', department: 'Cantal', city: 'Aurillac' },
  { id: '16', department: 'Charente', city: 'Angoulême' },
  { id: '17', department: 'Charente-Maritime', city: 'La Rochelle' },
  { id: '18', department: 'Cher', city: 'Bourges' },
  { id: '19', department: 'Corrèze', city: 'Tulle' },
  { id: '2A', department: 'Corse-du-Sud', city: 'Ajaccio' },
  { id: '2B', department: 'Haute-Corse', city: 'Bastia' },
  { id: '21', department: "Côte-d'Or", city: 'Dijon' },
  { id: '22', department: "Côtes d'Armor", city: 'Saint-Brieuc' },
  { id: '23', department: 'Creuse', city: 'Guéret' },
  { id: '24', department: 'Dordogne', city: 'Périgueux' },
  { id: '25', department: 'Doubs', city: 'Besançon' },
  { id: '26', department: 'Drôme', city: 'Valence' },
  { id: '27', department: 'Eure', city: 'Évreux' },
  { id: '28', department: 'Eure-et-Loir', city: 'Chartres' },
  { id: '29', department: 'Finistère', city: 'Quimper' },
  { id: '30', department: 'Gard', city: 'Nîmes' },
  { id: '31', department: 'Haute-Garonne', city: 'Toulouse' },
  { id: '32', department: 'Gers', city: 'Auch' },
  { id: '33', department: 'Gironde', city: 'Bordeaux' },
  { id: '34', department: 'Hérault', city: 'Montpellier' },
  { id: '35', department: 'Îlle-et-Vilaine', city: 'Rennes' },
  { id: '36', department: 'Indre', city: 'Châteauroux' },
  { id: '37', department: 'Indre-et-Loire', city: 'Tours' },
  { id: '38', department: 'Isère', city: 'Grenoble' },
  { id: '39', department: 'Jura', city: 'Lons-le-Saunier' },
  { id: '40', department: 'Landes', city: 'Mont-de-Marsan' },
  { id: '41', department: 'Loir-et-Cher', city: 'Blois' },
  { id: '42', department: 'Loire', city: 'Saint-Étienne' },
  { id: '43', department: 'Haute-Loire', city: 'Le Puy-en-Velay' },
  { id: '44', department: 'Loire-Atlantique', city: 'Nantes' },
  { id: '45', department: 'Loiret', city: 'Orléans' },
  { id: '46', department: 'Lot', city: 'Cahors' },
  { id: '47', department: 'Lot-et-Garonne', city: 'Agen' },
  { id: '48', department: 'Lozère', city: 'Mende' },
  { id: '49', department: 'Maine-et-Loire', city: 'Angers' },
  { id: '50', department: 'Manche', city: 'Saint-Lô' },
  { id: '51', department: 'Marne', city: 'Châlons-en-Champagne' },
  { id: '52', department: 'Haute-Marne', city: 'Chaumont' },
  { id: '53', department: 'Mayenne', city: 'Laval' },
  { id: '54', department: 'Meurthe-et-Moselle', city: 'Nancy' },
  { id: '55', department: 'Meuse', city: 'Bar-le-Duc' },
  { id: '56', department: 'Morbihan', city: 'Vannes' },
  { id: '57', department: 'Moselle', city: 'Metz' },
  { id: '58', department: 'Nièvre', city: 'Nevers' },
  { id: '59', department: 'Nord', city: 'Lille' },
  { id: '60', department: 'Oise', city: 'Beauvais' },
  { id: '61', department: 'Orne', city: 'Alençon' },
  { id: '62', department: 'Pas-de-Calais', city: 'Arras' },
  { id: '63', department: 'Puy-de-Dôme', city: 'Clermont-Ferrand' },
  { id: '64', department: 'Pyrénées-Atlantiques', city: 'Pau' },
  { id: '65', department: 'Hautes-Pyrénées', city: 'Tarbes' },
  { id: '66', department: 'Pyrénées-Orientales', city: 'Perpignan' },
  { id: '67', department: 'Bas-Rhin', city: 'Strasbourg' },
  { id: '68', department: 'Haut-Rhin', city: 'Colmar' },
  { id: '69', department: 'Rhône', city: 'Lyon' },
  { id: '70', department: 'Haute-Saône', city: 'Vesoul' },
  { id: '71', department: 'Saône-et-Loire', city: 'Mâcon' },
  { id: '72', department: 'Sarthe', city: 'Le Mans' },
  { id: '73', department: 'Savoie', city: 'Chambéry' },
  { id: '74', department: 'Haute-Savoie', city: 'Annecy' },
  { id: '75', department: 'Paris', city: 'Paris' },
  { id: '76', department: 'Seine-Maritime', city: 'Rouen' },
  { id: '77', department: 'Seine-et-Marne', city: 'Melun' },
  { id: '78', department: 'Yvelines', city: 'Versailles' },
  { id: '79', department: 'Deux-Sèvres', city: 'Niort' },
  { id: '80', department: 'Somme', city: 'Amiens' },
  { id: '81', department: 'Tarn', city: 'Albi' },
  { id: '82', department: 'Tarn-et-Garonne', city: 'Montauban' },
  { id: '83', department: 'Var', city: 'Toulon' },
  { id: '84', department: 'Vaucluse', city: 'Avignon' },
  { id: '85', department: 'Vendée', city: 'La Roche-sur-Yon' },
  { id: '86', department: 'Vienne', city: 'Poitiers' },
  { id: '87', department: 'Haute-Vienne', city: 'Limoges' },
  { id: '88', department: 'Vosges', city: 'Épinal' },
  { id: '89', department: 'Yonne', city: 'Auxerre' },
  { id: '90', department: 'Territoire-de-Belfort', city: 'Belfort' },
  { id: '91', department: 'Essonne', city: 'Évry' },
  { id: '92', department: 'Hauts-de-Seine', city: 'Nanterre' },
  { id: '93', department: 'Seine-Saint-Denis', city: 'Bobigny' },
  { id: '94', department: 'Val-de-Marne', city: 'Créteil' },
  { id: '95', department: "Val-d'Oise", city: 'Pontoise' },
];
