import type { State } from '@models/data/state';

export const usaStateData: State[] = [
  { id: 'AK', state: 'Alaska', capital: 'Juneau' },
  { id: 'HI', state: 'Hawaii', capital: 'Honolulu' },
  { id: 'AL', state: 'Alabama', capital: 'Montgomery' },
  { id: 'AR', state: 'Arkansas', capital: 'Little Rock' },
  { id: 'AZ', state: 'Arizona', capital: 'Phoenix' },
  { id: 'CA', state: 'California', capital: 'Sacramento' },
  { id: 'CO', state: 'Colorado', capital: 'Denver' },
  { id: 'CT', state: 'Connecticut', capital: 'Hartford' },
  { id: 'DE', state: 'Delaware', capital: 'Dover' },
  { id: 'FL', state: 'Florida', capital: 'Tallahassee' },
  { id: 'GA', state: 'Georgia', capital: 'Atlanta' },
  { id: 'IA', state: 'Iowa', capital: 'Des Moines' },
  { id: 'ID', state: 'Idaho', capital: 'Boise' },
  { id: 'IL', state: 'Illinois', capital: 'Springfield' },
  { id: 'IN', state: 'Indiana', capital: 'Indianapolis' },
  { id: 'KS', state: 'Kansas', capital: 'Topeka' },
  { id: 'KY', state: 'Kentucky', capital: 'Frankfort' },
  { id: 'LA', state: 'Louisiana', capital: 'Baton Rouge' },
  { id: 'MA', state: 'Massachusetts', capital: 'Boston' },
  { id: 'MD', state: 'Maryland', capital: 'Annapolis' },
  { id: 'ME', state: 'Maine', capital: 'Augusta' },
  { id: 'MI', state: 'Michigan', capital: 'Lansing' },
  { id: 'MN', state: 'Minnesota', capital: 'Saint Paul' },
  { id: 'MO', state: 'Missouri', capital: 'Jefferson City' },
  { id: 'MS', state: 'Mississippi', capital: 'Jackson' },
  { id: 'MT', state: 'Montana', capital: 'Helena' },
  { id: 'NC', state: 'North Carolina', capital: 'Raleigh' },
  { id: 'ND', state: 'North Dakota', capital: 'Bismarck' },
  { id: 'NE', state: 'Nebraska', capital: 'Lincoln' },
  { id: 'NH', state: 'New Hampshire', capital: 'Concord' },
  { id: 'NJ', state: 'New Jersey', capital: 'Trenton' },
  { id: 'NM', state: 'New Mexico', capital: 'Santa Fe' },
  { id: 'NV', state: 'Nevada', capital: 'Carson City' },
  { id: 'NY', state: 'New York', capital: 'Albany' },
  { id: 'OH', state: 'Ohio', capital: 'Columbus' },
  { id: 'OK', state: 'Oklahoma', capital: 'Oklahoma City' },
  { id: 'OR', state: 'Oregon', capital: 'Salem' },
  { id: 'PA', state: 'Pennsylvania', capital: 'Harrisburg' },
  { id: 'RI', state: 'Rhode Island', capital: 'Providence' },
  { id: 'SC', state: 'South Carolina', capital: 'Columbia' },
  { id: 'SD', state: 'South Dakota', capital: 'Pierre' },
  { id: 'TN', state: 'Tennessee', capital: 'Nashville' },
  { id: 'TX', state: 'Texas', capital: 'Austin' },
  { id: 'UT', state: 'Utah', capital: 'Salt Lake City' },
  { id: 'VA', state: 'Virginia', capital: 'Richmond' },
  { id: 'VT', state: 'Vermont', capital: 'Montpelier' },
  { id: 'WA', state: 'Washington', capital: 'Olympia' },
  { id: 'WI', state: 'Wisconsin', capital: 'Madison' },
  { id: 'WV', state: 'West Virginia', capital: 'Charleston' },
  { id: 'WY', state: 'Wyoming', capital: 'Cheyenne' },
];
