import type { State } from '@models/data/state';

export const usaStateData: State[] = [
  { id: 'AK', state: 'Alaska', city: 'Juneau' },
  { id: 'HI', state: 'Hawaii', city: 'Honolulu' },
  { id: 'AL', state: 'Alabama', city: 'Montgomery' },
  { id: 'AR', state: 'Arkansas', city: 'Little Rock' },
  { id: 'AZ', state: 'Arizona', city: 'Phoenix' },
  { id: 'CA', state: 'California', city: 'Sacramento' },
  { id: 'CO', state: 'Colorado', city: 'Denver' },
  { id: 'CT', state: 'Connecticut', city: 'Hartford' },
  { id: 'DE', state: 'Delaware', city: 'Dover' },
  { id: 'FL', state: 'Florida', city: 'Tallahassee' },
  { id: 'GA', state: 'Georgia', city: 'Atlanta' },
  { id: 'IA', state: 'Iowa', city: 'Des Moines' },
  { id: 'ID', state: 'Idaho', city: 'Boise' },
  { id: 'IL', state: 'Illinois', city: 'Springfield' },
  { id: 'IN', state: 'Indiana', city: 'Indianapolis' },
  { id: 'KS', state: 'Kansas', city: 'Topeka' },
  { id: 'KY', state: 'Kentucky', city: 'Frankfort' },
  { id: 'LA', state: 'Louisiana', city: 'Baton Rouge' },
  { id: 'MA', state: 'Massachusetts', city: 'Boston' },
  { id: 'MD', state: 'Maryland', city: 'Annapolis' },
  { id: 'ME', state: 'Maine', city: 'Augusta' },
  { id: 'MI', state: 'Michigan', city: 'Lansing' },
  { id: 'MN', state: 'Minnesota', city: 'Saint Paul' },
  { id: 'MO', state: 'Missouri', city: 'Jefferson City' },
  { id: 'MS', state: 'Mississippi', city: 'Jackson' },
  { id: 'MT', state: 'Montana', city: 'Helena' },
  { id: 'NC', state: 'North Carolina', city: 'Raleigh' },
  { id: 'ND', state: 'North Dakota', city: 'Bismarck' },
  { id: 'NE', state: 'Nebraska', city: 'Lincoln' },
  { id: 'NH', state: 'New Hampshire', city: 'Concord' },
  { id: 'NJ', state: 'New Jersey', city: 'Trenton' },
  { id: 'NM', state: 'New Mexico', city: 'Santa Fe' },
  { id: 'NV', state: 'Nevada', city: 'Carson City' },
  { id: 'NY', state: 'New York', city: 'Albany' },
  { id: 'OH', state: 'Ohio', city: 'Columbus' },
  { id: 'OK', state: 'Oklahoma', city: 'Oklahoma City' },
  { id: 'OR', state: 'Oregon', city: 'Salem' },
  { id: 'PA', state: 'Pennsylvania', city: 'Harrisburg' },
  { id: 'RI', state: 'Rhode Island', city: 'Providence' },
  { id: 'SC', state: 'South Carolina', city: 'Columbia' },
  { id: 'SD', state: 'South Dakota', city: 'Pierre' },
  { id: 'TN', state: 'Tennessee', city: 'Nashville' },
  { id: 'TX', state: 'Texas', city: 'Austin' },
  { id: 'UT', state: 'Utah', city: 'Salt Lake City' },
  { id: 'VA', state: 'Virginia', city: 'Richmond' },
  { id: 'VT', state: 'Vermont', city: 'Montpelier' },
  { id: 'WA', state: 'Washington', city: 'Olympia' },
  { id: 'WI', state: 'Wisconsin', city: 'Madison' },
  { id: 'WV', state: 'West Virginia', city: 'Charleston' },
  { id: 'WY', state: 'Wyoming', city: 'Cheyenne' },
];
